name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clear previous data 
      run: rm -rf /Users/runner/Library/Developer/Xcode/DerivedData/*
    - name: Run lanes
      run: fastlane tests
